name: 'Feature Request'
description: A new feature or task
labels: ["enhancement"]
milestone: ["Backlog"]
projects: ["engineering_backlog"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

