name: 'Feature Request'
description: A new feature or task
labels: ["enhancement"]
projects: ["enabletechnologies/1"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

