name: 'Add new dependency'
description: A new python or ui library
title: "Add dependency -  "
labels: ["dependencies"]
projects: ["enabletechnologies/1"]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Sanity Checks
      description: Please confirm and check all the following options.
      options:
        - label: Is it absolutely necessary to add this library ? Can you use an existing (possibly indirect) dependency instead or write your own code?
          required: true
        - label: Are you evaluating the intended version? Ensure you are evaluating the intended version of the software, not a personal fork nor an attacker-controlled fork
          required: true
        - label: Is it maintained? Has significant recent activity (e.g., commits,releases, issues fixed , pull requests) occurred within the last year? 
          required: true
        - label: Is there evidence that its developers work to make it secure? Are the package dependencies are (relatively) up to date?
          required: true
        - label: Does it have significant use? Does it have sufficient github stars and forks.
          required: true
        - label: Have you ensured library has the correct license? Ensure there is no limited or commercial use. In that case more discussions are required
          required: true
        - label: Have you gone through the open source guidelines in [Secure coding guidelines](https://github.com/enabletechnologies/common/blob/develop/docs/internal/secure_coding_guidelines.md#selecting-open-source).
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      required: true
      description: Describe the library and why it is required
    validations:
      required: true
  - type: textarea
    id: similar_libraries
    attributes:
      label: Similar Library
      description: Provide links to any other libraries which are similar.
    validations:
      required: true
  - type: textarea
    id: deps
    attributes:
      label: Dependencies
      description: Provide list of the all production dependency for this library
    validations:
      required: true
  - type: textarea
    id: code_evaluation
    attributes:
      label: What is your evaluation of its code?
      description: Provide a brief review of software source code, and its changes over time. It can give you some insight
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide links to references about the library.
    validations:
      required: true
