blank_issues_enabled: false
contact_links:
  - name: Security Contact
    about: Please report security vulnerabilities to cloudops@enable-technologies.com
  - name: An Idea or General Topic
    about: Create a discussion in GitHub Discussions.
    url: https://github.com/orgs/enabletechnologies/discussions